baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Jaehyun Lee
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: About
          url: about/
          weight: 5 
        - name: Research
          url: research/
          weight: 2
        - name: Teaching
          url: teaching/
          weight: 3
        - name: CV
          url: cv/
          weight: 4 

params:
    description: "Jaehyun Lee's Academic Website"
    author: Jaehyun Lee
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "March 2026"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jaehyun Lee
          subtitle: "I'm a PhD Candidate in the Department of Logic and Philosophy of Science at University of California, Irvine. Before coming to UCI, I completed a BA in Philosophy at Boğaziçi University in Istanbul, Turkiye. I work primarily in the philosophy of science, particularly in scientific explanations. I’m also interested in evolutionary biology, philosophy of social science, philosophy of language, and ethics."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
                    - name: About
                      url: about/
                    - name: Research
                      url: research/
                    - name: Teaching
                      url: teaching/
                    - name: CV
                      url: cv/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:jaehyun.l@uci.edu

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jaehyun Lee"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
